USE fitness_db;

INSERT INTO `exercises` (`name`, `description`, `video_url`) VALUES
('Barbell Back Squat', 'Squatting with a barbell resting on the upper back (traps). Works quads, glutes, hamstrings, core.', 'VZ90qWlfQUE'),
('Barbell Front Squat', 'Squatting with a barbell resting across the front of the shoulders. Emphasizes quads and core stability.', '7nDvE3LdiAc'),
('Conventional Deadlift', 'Lifting a barbell from the floor until standing upright, with feet hip-width apart. Works entire posterior chain, back, legs, grip.', 'AweC3UaM14o'),
('Sumo Deadlift', 'Lifting a barbell from the floor with a wide stance and grip inside the legs. Works glutes, hamstrings, hips, back.', 'pfSMst14EFk'),
('Barbell Bench Press', 'Lying on a bench and pressing a barbell up from the chest. Works chest, shoulders, triceps.', 'x2oPR-49QNc'),
('Barbell Incline Bench Press', 'Bench pressing on an inclined bench. Emphasizes the upper chest.', 'lJ2o89kcnxY'),
('Standing Overhead Press (OHP)', 'Pressing a barbell straight up overhead from the shoulders while standing. Works shoulders, triceps, core.', 'QAQ64hK4Xxs'),
('Barbell Row (Bent-Over)', 'Pulling a barbell towards the torso while bent over with a flat back. Works lats, rhomboids, biceps, lower back.', '6FZHJGzMFEc'),
('Push-up', 'Lowering and raising the body using the arms while keeping the body straight. Works chest, shoulders, triceps, core.', 'Kn5meP3j1z0'),
('Pull-up', 'Pulling the body up using an overhand grip on a bar until the chin clears it. Works lats, biceps, back.', 'mM8raHJoSl4'),
('Lunge', 'Stepping forward, backward, or sideways and lowering the hips until both knees are bent at a 90-degree angle. Works quads, glutes, hamstrings.', '5kOp-mlmhko'),
('Plank', 'Holding the torso straight and rigid, parallel to the floor, supported by forearms/hands and toes. Works core stability.', 'pvIjsG5Svck'),
('Side Plank', 'Holding the body on its side in a straight line supported by one forearm and the side of the foot. Works obliques, core stability.', 'N_s9em1xTqU'),
('Crunch', 'Lying on the back and lifting the upper torso towards the knees. Works abdominal muscles.', 'MKmrqcoCZ-M'),
('Leg Raise', 'Lying on the back and lifting the legs up towards the ceiling while keeping them straight. Works lower abdominal muscles.', 'U4L_6JEv9Jg'),
('Burpee', 'A full body exercise involving a squat, push-up, and jump. Works cardio, legs, chest, core.', 'qLBImHhCXSw'),
('Dip (Parallel Bars)', 'Lowering and raising the body between parallel bars. Works chest, shoulders, triceps.', 'l41SoWZiowI'),
('Jumping Jacks', 'A full body cardio exercise involving jumping to a position with legs spread wide and hands touching overhead.', 'uLVt6u15L98'),
('High Knees', 'Running in place while lifting the knees as high as possible towards the chest. Cardio exercise.', 'x4ISQVdWOjA'),
('Dumbbell Bench Press', 'Bench pressing using dumbbells instead of a barbell. Allows greater range of motion.', 'QsYre__-aro'),
('Dumbbell Incline Bench Press', 'Incline bench pressing with dumbbells.', 'oZVCBM9f8Eo'),
('Dumbbell Row (One-Arm)', 'Supporting the body with one hand and knee on a bench, pulling a dumbbell towards the torso with the other arm.', 'dFzUjzfih7k'),
('Dumbbell Shoulder Press', 'Pressing dumbbells overhead while seated or standing.', 'TsduLWuhlFM'),
('Dumbbell Bicep Curl', 'Curling dumbbells towards the shoulders, keeping elbows tucked in.', 'ykJmrZ5v0Oo'),
('Dumbbell Hammer Curl', 'Bicep curl performed with palms facing each other (neutral grip). Works biceps and brachialis.', 'BRVDS6HVR9Q'),
('Dumbbell Triceps Extension (Overhead)', 'Extending dumbbells overhead by straightening the elbows while seated or standing.', '_eqcf0S1uM4'),
('Dumbbell Lateral Raise', 'Raising dumbbells out to the sides until parallel with the floor. Works side deltoids.', 'XPPfnSEATJA'),
('Dumbbell Front Raise', 'Raising dumbbells straight out in front of the body. Works front deltoids.', 'hRJ6tR5-if0'),
('Dumbbell Flyes', 'Lying on a bench and lowering dumbbells out to the sides with elbows slightly bent. Works chest.', 'Nhvz9EzdJ4U'),
('Goblet Squat', 'Squatting while holding a single dumbbell vertically against the chest.', '9W5KAqHfDe8'),
('Leg Press', 'Pushing a weighted platform away using the legs while seated in a machine.', 'VFk3RzndUEc'),
('Lat Pulldown', 'Pulling a bar down towards the chest while seated in a machine. Works lats, back.', 'SALxEARiMkw'),
('Chest Press Machine', 'Pushing handles forward while seated in a chest press machine.', 'IvCU-PD5VpI'),
('Leg Extension Machine', 'Extending the lower legs against resistance while seated. Isolates quadriceps.', '4ZDm5EbiFI8'),
('Hamstring Curl Machine (Lying)', 'Curling the lower legs towards the glutes against resistance while lying face down.', 'Orxowest56U'),
('Seated Cable Row', 'Pulling a handle towards the torso while seated using a cable machine. Works back, biceps.', 'vwHG9Jfu4sw'),
('Cable Fly / Crossover', 'Bringing cable handles together in front of the body. Works chest.', '8Um35Es-ROE'),
('Standing Calf Raise', 'Raising the heels against resistance while standing on a platform.', 'zNcD6cq1jnM'),
('Pec Deck Machine', 'Bringing padded levers together using the chest muscles while seated.', '10hg4LAa7UQ'),
('Machine Shoulder Press', 'Pressing handles overhead while seated in a shoulder press machine.', 'WvLMauqrnK8'),
('Elliptical Trainer', 'Using an elliptical machine for a low-impact cardio workout.', 'EesEvYohy5o'),
('Rowing Machine (Ergometer)', 'Simulating rowing using a machine. Full body cardio and strength.', 'kjcZlAp3fsc'),
('Full Body Strech' , 'Full body stretch routine to improve flexibility and mobility.', 'FI51zRzgIe4');